name:                lowarn-update-hnes-v159-v160
version:             1.0.0
github:              "lowarn-dsu/lowarn-hnes"
license:             BSD3
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

dependencies:
- base >= 4.7 && < 5
- containers
- lowarn
- lowarn-transformer
- name: lowarn-version-hnes-v159
  mixin:
  - (Emulator.Nes as PreviousVersion.Emulator.Nes, Emulator.Mapper as PreviousVersion.Emulator.Mapper, Emulator.Mapper.Mapper2 as PreviousVersion.Emulator.Mapper.Mapper2, Emulator.Cartridge as PreviousVersion.Emulator.Cartridge, EntryPoint_hnes as PreviousVersion.EntryPoint)
- name: lowarn-version-hnes-v160
  mixin:
  - (Emulator.Nes as NextVersion.Emulator.Nes, Emulator.Mapper as NextVersion.Emulator.Mapper, Emulator.Mapper.Mapper2 as NextVersion.Emulator.Mapper.Mapper2, Emulator.Cartridge as NextVersion.Emulator.Cartridge, EntryPoint_hnes as NextVersion.EntryPoint)

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
