name:                lowarn-update-hnes-v155-v156
version:             1.0.0
github:              "lowarn-dsu/lowarn-hnes"
license:             BSD3
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

dependencies:
- base >= 4.7 && < 5
- containers
- lowarn
- lowarn-transformer
- name: lowarn-version-hnes-v155
  mixin:
  - (Emulator.Nes as PreviousVersion.Emulator.Nes, EntryPoint_hnes as PreviousVersion.EntryPoint)
- name: lowarn-version-hnes-v156
  mixin:
  - (Emulator.Nes as NextVersion.Emulator.Nes, EntryPoint_hnes as NextVersion.EntryPoint)

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
